### ISSUE TITLE
Binary installation documentation bugs

### ISSUE THREAD

**Issue by protoben** [dominique-unruh/qrhl-tool#15]
I just managed to get qrhl-tool running. In doing so, I ran into a couple of issues with the installation instructions in README.md.

First, the github downloads directory does not seem to have a binary development snapshot as the README suggests. I succeeded at installing `qrhl-0.6.zip` using Isabelle 2019.

Second, the README claims that the path to AFP should be set in `qrhl-tool.conf` as `afp-home`, but this results in AFP not being found. It seems to need to be set as `afp-root` instead.

**Comment by dominique-unruh** [comment]
@protoben I agree with the comment about `afp-root`.

I don't understand the point about the "binary development snapshot", though. Can you explain where it indicates that there should be binary development snapshot included? In https://github.com/dominique-unruh/qrhl-tool/releases/tag/v0.6, it says "Isabelle2021 must be installed. Download it at ..." but maybe I misunderstood your issue.

**Comment by dominique-unruh** [comment]
Maybe you meant this:
> The first step of the proof script (isabelle.) will take very long upon first activation, because it will download and build Isabelle.

That is indeed outdated and will be replaced in the next release by "will build all required Isabelle theories".
