### ISSUE TITLE
Sbt test fails due to Bad Parent Session

### ISSUE THREAD

**Issue by ianhhlee** [dominique-unruh/qrhl-tool#59]
Complex_Bounded_Operators which is a WARN during sbt compilation but fails during test

<img width="574" alt="qrhltool_error" src="https://user-images.githubusercontent.com/62287696/184528721-9effe5d6-c0b9-43fc-b4a2-85c8bf432254.PNG">

**Comment by dominique-unruh** [comment]
I think this is because your local Isabelle distribution has no AFP configured. Configuring `afp-roof` in `qrhl-tool.conf` should help.

**Comment by ianhhlee** [comment]
There was an error in the documentation which indicated that the afp should be configured as _**afp-home**_. Changing that to _**afp-root**_ allows the build to proceed.

**Comment by dominique-unruh** [comment]
I assume you mean on https://dominique-unruh.github.io/qrhl-tool/install.html? Unless there is another place where it's wrong, it's fixed now.

**Comment by ianhhlee** [comment]
Yes. That's right. Good that it was cleared up.
