### ISSUE TITLE
Methods that does wp, skip, rnd, simp automatically

### ISSUE THREAD

**Issue by tvcarstens** [dominique-unruh/qrhl-tool#9]
Rough algo:

* For assignments, do wp.
* For <$ on both sides with everything the same, do rnd.
* For identical call on both sides, to equal.
* For skip on both sides, do skip.
* For result of skip, do simp (with the lemmas that are given to the method)
* Repeat till it doesn't work.

**Comment by dominique-unruh** [comment]
No plan to introduce such a tactic, but the equal-tactic now can do whole blocks of identical code.
